import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNavBar from "@/components/SideNavBar";
import MainBar from "@/components/MainBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full w-screen antialiased `}>
      <body className="flex">
        <div>
          <SideNavBar />
        </div>
        <div className="flex flex-col w-full">
          <MainBar />
          {children}
        </div>
      </body>
    </html>
  );
}
